// <auto-generated />
using JobleGlobal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace JobleGlobal.Models.Migrations
{
    [DbContext(typeof(JobleDBContext))]
    [Migration("20180416093112_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobleGlobal.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactNumber1");

                    b.Property<string>("ContactNumber2");

                    b.Property<string>("Email1");

                    b.Property<string>("Email2");

                    b.Property<string>("Name");

                    b.Property<string>("PrimaryContactPersonGuid");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("JobleGlobal.Models.OrganisationPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("IsActive");

                    b.Property<int>("OrganisationId");

                    b.Property<int>("PlanId");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("PlanId");

                    b.ToTable("OrganisationPlan");
                });

            modelBuilder.Entity("JobleGlobal.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cost");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("JobleGlobal.Models.OrganisationPlan", b =>
                {
                    b.HasOne("JobleGlobal.Models.Customer", "Organisation")
                        .WithMany("OrganisationPlan")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JobleGlobal.Models.Plan", "Plan")
                        .WithMany("OrganisationPlan")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
